language: python
dist: trusty
sudo: required

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - sudo apt-get update
  - pip install --disable-pip-version-check --upgrade pip

install:
  - sudo apt-get install devscripts python-setuptools debhelper python-all python3-all python3-setuptools python-usb python3-usb python-pyscard python3-pyscard
  - pip install pre-commit

script:
  - pre-commit run --all-files
  - pip install -e .

after_success:
  - debuild -us -uc
  - mkdir deploy
  - mv ../*.deb deploy/yubikey-manager-$TRAVIS_BRANCH-HEAD.deb

deploy:
  provider: s3
  access_key_id: "$AWS_KEY_ID"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "$AWS_BUCKET"
  skip_cleanup: true
  acl: public-read
  region: eu-west-1
  local-dir: "deploy/"
  upload-dir: "yubikey-manager"
  on:
    all_branches: true
