language: python
dist: trusty
sudo: required

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - sudo add-apt-repository -y ppa:yubico/stable
  - sudo apt-get update
  - sudo apt-get install -y swig libpcsclite-dev libykpers-1-dev libu2f-host-dev
 
install:
  - pip install --disable-pip-version-check --upgrade pip
  - pip install pre-commit
  - pip install -e .

script:
  - pre-commit run --all-files
