language: python
dist: trusty
sudo: required

services:
  - docker

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - docker build -t xenial docker/xenial
  - sudo apt-get update
  - pip install --disable-pip-version-check --upgrade pip

install:
  - sudo apt-get install swig libpcsclite-dev
  - pip install pre-commit
  - pip install -e .

script:
  - pre-commit run --all-files
  - python setup.py test

after_success:
  - mkdir deploy
  - id=$(docker create xenial)
  - docker cp $id:/yubikey-manager-debian-builds.tar.gz deploy/
  - mv deploy/yubikey-manager-debian-builds.tar.gz deploy/yubikey-manager-debian-builds-$TRAVIS_BRANCH-HEAD.tar.gz

deploy:
  provider: s3
  access_key_id: "$AWS_KEY_ID"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "$AWS_BUCKET"
  skip_cleanup: true
  acl: public-read
  region: eu-west-1
  local-dir: "deploy/"
  upload-dir: "yubikey-manager"
  on:
    all_branches: true
