# appveyor.yml

# Building, testing and deployment for Windows

# Syntax for this file:
# https://www.appveyor.com/docs/appveyor-yml

image: Visual Studio 2015

environment:
  LIBU2F_HOST_VERSION: "1.1.4"
  YKPERS_VERSION: "1.19.0"
  LIBUSB_VERSION: "1.0.21"

  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

matrix:
  fast_finish: true

init:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

install:
  - choco install swig -y
  - choco upgrade swig

  - ps: wget "https://developers.yubico.com/yubikey-personalization/Releases/ykpers-$env:YKPERS_VERSION-win32.zip" -OutFile "ykpers-$env:YKPERS_VERSION-win32.zip"
  - 7z x ykpers-%YKPERS_VERSION%-win32.zip -o".\ykpers"
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\ykpers\bin

  - ps: Invoke-WebRequest "http://prdownloads.sourceforge.net/libusb/libusb-$env:LIBUSB_VERSION.7z" -OutFile "libusb-$env:LIBUSB_VERSION.7z" -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome
  - 7z x libusb-%LIBUSB_VERSION%.7z -o".\libusb"
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\libusb\MS32\dll

build_script:
  - pip install -e .
  - ykman -v

test_script:
  - python setup.py test
