# appveyor.yml

# Building, testing and deployment for Windows

# Syntax for this file:
# https://www.appveyor.com/docs/appveyor-yml

image: Visual Studio 2015

environment:
  LIBU2F_HOST_VERSION: "1.1.3"
  YKPERS_VERSION: "1.18.0"
  LIBUSB_VERSION: "1.0.21"

  #  matrix:
  #  - PYTHON: "C:\\Python27"
  #  - PYTHON: "C:\\Python27-x64"
  #  - PYTHON: "C:\\Python35"
  #  - PYTHON: "C:\\Python35-x64"
  #  - PYTHON: "C:\\Python36"
  #  - PYTHON: "C:\\Python36-x64"


# matrix:
  # fast_finish: true

init:
  - set PATH=%PATH%;C:\Python36\Scripts;
  # - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

install:
  - git submodule update --init --recursive

  - rm .\ykman\yubicommon
  - xcopy /i /e .\vendor\yubicommon\yubicommon .\ykman\yubicommon

  - choco install swig -y
  - choco upgrade swig

  - ps: wget DownloadFile "https://developers.yubico.com/libu2f-host/Releases/libu2f-host-$env:LIBU2F_HOST_VERSION-win32.zip" -OutFile "libu2f-host-$env:LIBU2F_HOST_VERSION-win32.zip"
  - 7z x libu2f-host-%LIBU2F_HOST_VERSION%-win32.zip -o".\libu2f-host" 
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\libu2f-host\bin

  - ps: wget DownloadFile "https://developers.yubico.com/yubikey-personalization/Releases/ykpers-$env:YKPERS_VERSION-win32.zip" -OutFile "ykpers-$env:YKPERS_VERSION%-win32.zip"
  - 7z x ykpers-%YKPERS_VERSION%-win32.zip -o".\ykpers"
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\ykpers\bin

  - ps: wget "http://prdownloads.sourceforge.net/libusb/libusb-$env:LIBUSB_VERSION.7z" -OutFile "libusb-$env:LIBUSUSB_VERSION.7z"
  - 7z x libusb-%LIBUSB_VERSION%.7z -o".\libusb
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\libusb\MS32\dll

build_script:
  - pip3 install -e .
  - ykman -v

test_script:
  - python setup.py test
