# appveyor.yml

# Building, testing and deployment for Windows

# Syntax for this file:
# https://www.appveyor.com/docs/appveyor-yml

image: Visual Studio 2015


init:
  # Add python to PATH
  - set PATH=%PATH%;C:\Python36\Scripts;
  - set LIBU2F_HOST_VERSION=1.1.3
  - set YKPERS_VERSION=1.18.0

install:
  - git submodule update --init --recursive

  - rm .\ykman\yubicommon
  - xcopy /i /e .\vendor\yubicommon\yubicommon .\ykman\yubicommon

  - choco install swig -y
  - choco upgrade swig

  - ps: wget https://developers.yubico.com/libu2f-host/Releases/libu2f-host-%LIBU2F_HOST_VERSION%-win32.zip -OutFile libu2f-host-%LIBU2F_HOST_VERSION%-win32.zip
  - 7z x libu2f-host-%LIBU2F_HOST_VERSION%-win32.zip -o".\libu2f-host" 
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\libu2f-host\bin

  - ps: wget https://developers.yubico.com/yubikey-personalization/Releases/ykpers-%YKPERS_VERSION%-win32.zip -OutFile ykpers-%YKPERS_VERSION%-win32.zip  
  - 7z x ykpers-%YKPERS_VERSION%-win32.zip -o".\ykpers"
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\ykpers\bin

  - ps: wget https://s3.eu-central-1.amazonaws.com/yubico-deps/yubikey-manager-qt/libusb-1.0.20.7z -OutFile libusb-1.0.20.7z
  - 7z x libusb-1.0.20.7z -o".\libusb
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\libusb\MS32\dll

build_script:
  - pip3 install -e .
  - ykman -v
